
functional:
 -Пользователь должен иметь возможность создать аккаунт, войти в систему и настроить свой профиль (выбрать аватар, указать основной язык программирования).
  - Система должна подбирать равных по рейтингу соперников и автоматически создавать для них игровую комнату.
  - Система должна фиксировать время отправки финального верного решения и мгновенно завершать матч, присуждая победу тому,кто справился быстрее.
  - Внутри игровой комнаты пользователю должен быть доступен встроенный текстовый редактор с подсветкой синтаксиса выбранного языка программирования.
  - Система должна компилировать/интерпретировать написанный пользователем код, прогонять его через скрытые тесты и возвращать результат (пройдено/ошибка).
 non-functional:
  -Платформа должна поддерживать одновременное проведение не менее 1 000 игровых дуэлей без падения производительности компиляторов.
  - Веб-интерфейс и игровой редактор кода должны корректно работать и отображаться во всех актуальных версиях браузеров Chrome, Firefox, Safari.
  - Задержка передачи состояния экрана соперника и игрового таймера через WebSocket не должна превышать 100 мс.
 implicit:
  - Если у игрока на несколько секунд пропал интернет или он случайно перезагрузил страницу,написанный им код не должен стереться из редактора при восстановлении сессии.
  - Если один из игроков закрыл вкладку и не возвращается в игру более 2 минут, матч должен автоматически завершаться техническим поражением ушедшего,чтобы не держать второго игрока в бесконечном ожидании.
  - Обоим игрокам в одной комнате должна выдаваться абсолютно идентичная задача с одинаковыми входными данными и набором тестов.
   
